// AUTO-GENERATED by scripts/generateLevels.js — do not edit by hand.
// Every level below has been proven to have EXACTLY ONE solution by the
// exact solver in src/game/solver.js before being written to this file.
// The "solution" field exists for development/testing/verification only
// and must never be shown to the player.

export const LEVELS = [
  {
    "id": 1,
    "size": 4,
    "checkpoints": [
      {
        "number": 1,
        "row": 3,
        "col": 3
      },
      {
        "number": 2,
        "row": 3,
        "col": 0
      },
      {
        "number": 3,
        "row": 0,
        "col": 3
      }
    ],
    "walls": [
      {
        "row": 0,
        "col": 1,
        "direction": "right"
      }
    ],
    "solution": [
      [
        3,
        3
      ],
      [
        3,
        2
      ],
      [
        3,
        1
      ],
      [
        3,
        0
      ],
      [
        2,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        2,
        3
      ],
      [
        1,
        3
      ],
      [
        1,
        2
      ],
      [
        0,
        2
      ],
      [
        0,
        3
      ]
    ],
    "difficulty": 4,
    "difficultyRaw": 46.6
  },
  {
    "id": 2,
    "size": 4,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "row": 3,
        "col": 0
      },
      {
        "number": 3,
        "row": 1,
        "col": 3
      }
    ],
    "walls": [
      {
        "row": 1,
        "col": 0,
        "direction": "right"
      }
    ],
    "solution": [
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        2,
        3
      ],
      [
        2,
        2
      ],
      [
        2,
        1
      ],
      [
        1,
        1
      ],
      [
        1,
        2
      ],
      [
        0,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ]
    ],
    "difficulty": 4,
    "difficultyRaw": 45.9
  },
  {
    "id": 3,
    "size": 4,
    "checkpoints": [
      {
        "number": 1,
        "row": 1,
        "col": 1
      },
      {
        "number": 2,
        "row": 3,
        "col": 3
      },
      {
        "number": 3,
        "row": 0,
        "col": 3
      },
      {
        "number": 4,
        "row": 3,
        "col": 0
      }
    ],
    "walls": [
      {
        "row": 1,
        "col": 1,
        "direction": "right"
      }
    ],
    "solution": [
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        2,
        3
      ],
      [
        2,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        3
      ],
      [
        0,
        3
      ],
      [
        0,
        2
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ]
    ],
    "difficulty": 4,
    "difficultyRaw": 46.6
  },
  {
    "id": 4,
    "size": 4,
    "checkpoints": [
      {
        "number": 1,
        "row": 2,
        "col": 2
      },
      {
        "number": 2,
        "row": 0,
        "col": 1
      },
      {
        "number": 3,
        "row": 1,
        "col": 3
      },
      {
        "number": 4,
        "row": 3,
        "col": 0
      }
    ],
    "walls": [
      {
        "row": 0,
        "col": 1,
        "direction": "right"
      }
    ],
    "solution": [
      [
        2,
        2
      ],
      [
        2,
        1
      ],
      [
        2,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        1,
        2
      ],
      [
        0,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        3,
        2
      ],
      [
        3,
        1
      ],
      [
        3,
        0
      ]
    ],
    "difficulty": 4,
    "difficultyRaw": 41.9
  },
  {
    "id": 5,
    "size": 4,
    "checkpoints": [
      {
        "number": 1,
        "row": 3,
        "col": 1
      },
      {
        "number": 2,
        "row": 1,
        "col": 2
      },
      {
        "number": 3,
        "row": 0,
        "col": 3
      },
      {
        "number": 4,
        "row": 1,
        "col": 0
      }
    ],
    "walls": [],
    "solution": [
      [
        3,
        1
      ],
      [
        3,
        0
      ],
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        1,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        2,
        3
      ],
      [
        1,
        3
      ],
      [
        0,
        3
      ],
      [
        0,
        2
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ]
    ],
    "difficulty": 4,
    "difficultyRaw": 45
  },
  {
    "id": 6,
    "size": 5,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "row": 3,
        "col": 4
      },
      {
        "number": 3,
        "row": 4,
        "col": 1
      },
      {
        "number": 4,
        "row": 2,
        "col": 2
      }
    ],
    "walls": [
      {
        "row": 0,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 1,
        "col": 3,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 4,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 2,
        "direction": "down"
      }
    ],
    "solution": [
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        3
      ],
      [
        0,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        4,
        3
      ],
      [
        4,
        2
      ],
      [
        4,
        1
      ],
      [
        4,
        0
      ],
      [
        3,
        0
      ],
      [
        2,
        0
      ],
      [
        1,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        2,
        2
      ]
    ],
    "difficulty": 5,
    "difficultyRaw": 58.2
  },
  {
    "id": 7,
    "size": 5,
    "checkpoints": [
      {
        "number": 1,
        "row": 4,
        "col": 0
      },
      {
        "number": 2,
        "row": 4,
        "col": 4
      },
      {
        "number": 3,
        "row": 1,
        "col": 3
      },
      {
        "number": 4,
        "row": 0,
        "col": 0
      }
    ],
    "walls": [
      {
        "row": 1,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 2,
        "direction": "down"
      }
    ],
    "solution": [
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        3,
        4
      ],
      [
        2,
        4
      ],
      [
        1,
        4
      ],
      [
        0,
        4
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        1,
        2
      ],
      [
        0,
        2
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        3,
        2
      ],
      [
        3,
        1
      ],
      [
        3,
        0
      ],
      [
        2,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        0
      ]
    ],
    "difficulty": 5,
    "difficultyRaw": 59.8
  },
  {
    "id": 8,
    "size": 5,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 4
      },
      {
        "number": 2,
        "row": 1,
        "col": 1
      },
      {
        "number": 3,
        "row": 4,
        "col": 0
      },
      {
        "number": 4,
        "row": 4,
        "col": 4
      }
    ],
    "walls": [
      {
        "row": 2,
        "col": 3,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 1,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 3,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 1,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 3,
        "direction": "down"
      }
    ],
    "solution": [
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        1,
        3
      ],
      [
        0,
        3
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        1
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        4,
        3
      ],
      [
        3,
        3
      ],
      [
        3,
        2
      ],
      [
        2,
        2
      ],
      [
        2,
        3
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ]
    ],
    "difficulty": 5,
    "difficultyRaw": 59.8
  },
  {
    "id": 9,
    "size": 5,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "row": 4,
        "col": 0
      },
      {
        "number": 3,
        "row": 2,
        "col": 1
      },
      {
        "number": 4,
        "row": 4,
        "col": 4
      },
      {
        "number": 5,
        "row": 0,
        "col": 4
      }
    ],
    "walls": [
      {
        "row": 2,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 4,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 3,
        "direction": "right"
      }
    ],
    "solution": [
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        1,
        2
      ],
      [
        1,
        1
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        3,
        1
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        3,
        4
      ],
      [
        3,
        3
      ],
      [
        2,
        3
      ],
      [
        2,
        4
      ],
      [
        1,
        4
      ],
      [
        0,
        4
      ]
    ],
    "difficulty": 5,
    "difficultyRaw": 59.2
  },
  {
    "id": 10,
    "size": 5,
    "checkpoints": [
      {
        "number": 1,
        "row": 2,
        "col": 2
      },
      {
        "number": 2,
        "row": 4,
        "col": 0
      },
      {
        "number": 3,
        "row": 3,
        "col": 4
      },
      {
        "number": 4,
        "row": 0,
        "col": 4
      },
      {
        "number": 5,
        "row": 0,
        "col": 0
      }
    ],
    "walls": [
      {
        "row": 2,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 3,
        "direction": "down"
      },
      {
        "row": 0,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 2,
        "direction": "right"
      }
    ],
    "solution": [
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        3,
        1
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        3,
        4
      ],
      [
        3,
        3
      ],
      [
        2,
        3
      ],
      [
        2,
        4
      ],
      [
        1,
        4
      ],
      [
        0,
        4
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        1,
        2
      ],
      [
        0,
        2
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        2,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        0
      ]
    ],
    "difficulty": 5,
    "difficultyRaw": 56.6
  },
  {
    "id": 11,
    "size": 5,
    "checkpoints": [
      {
        "number": 1,
        "row": 4,
        "col": 0
      },
      {
        "number": 2,
        "row": 2,
        "col": 2
      },
      {
        "number": 3,
        "row": 0,
        "col": 1
      },
      {
        "number": 4,
        "row": 1,
        "col": 4
      },
      {
        "number": 5,
        "row": 4,
        "col": 4
      }
    ],
    "walls": [
      {
        "row": 3,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 1,
        "col": 0,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 4,
        "direction": "down"
      },
      {
        "row": 0,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 2,
        "direction": "right"
      }
    ],
    "solution": [
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        3,
        2
      ],
      [
        3,
        1
      ],
      [
        3,
        0
      ],
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        1
      ],
      [
        1,
        0
      ],
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        0,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ]
    ],
    "difficulty": 5,
    "difficultyRaw": 61
  },
  {
    "id": 12,
    "size": 5,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "row": 2,
        "col": 1
      },
      {
        "number": 3,
        "row": 1,
        "col": 4
      },
      {
        "number": 4,
        "row": 4,
        "col": 0
      },
      {
        "number": 5,
        "row": 3,
        "col": 3
      }
    ],
    "walls": [
      {
        "row": 0,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 2,
        "col": 1,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 2,
        "col": 0,
        "direction": "down"
      },
      {
        "row": 1,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 3,
        "direction": "right"
      }
    ],
    "solution": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        1,
        1
      ],
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        3
      ],
      [
        0,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        4,
        3
      ],
      [
        4,
        2
      ],
      [
        4,
        1
      ],
      [
        4,
        0
      ],
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        2,
        2
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ]
    ],
    "difficulty": 5,
    "difficultyRaw": 56.5
  },
  {
    "id": 13,
    "size": 5,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 4
      },
      {
        "number": 2,
        "row": 4,
        "col": 4
      },
      {
        "number": 3,
        "row": 2,
        "col": 1
      },
      {
        "number": 4,
        "row": 4,
        "col": 0
      },
      {
        "number": 5,
        "row": 0,
        "col": 0
      },
      {
        "number": 6,
        "row": 1,
        "col": 3
      }
    ],
    "walls": [
      {
        "row": 2,
        "col": 3,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 2,
        "direction": "down"
      }
    ],
    "solution": [
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        4,
        3
      ],
      [
        3,
        3
      ],
      [
        2,
        3
      ],
      [
        2,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        4,
        1
      ],
      [
        4,
        0
      ],
      [
        3,
        0
      ],
      [
        2,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ]
    ],
    "difficulty": 5,
    "difficultyRaw": 59
  },
  {
    "id": 14,
    "size": 5,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 4
      },
      {
        "number": 2,
        "row": 0,
        "col": 0
      },
      {
        "number": 3,
        "row": 2,
        "col": 1
      },
      {
        "number": 4,
        "row": 2,
        "col": 3
      },
      {
        "number": 5,
        "row": 4,
        "col": 0
      },
      {
        "number": 6,
        "row": 4,
        "col": 4
      }
    ],
    "walls": [
      {
        "row": 0,
        "col": 3,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 4,
        "direction": "down"
      },
      {
        "row": 0,
        "col": 2,
        "direction": "down"
      }
    ],
    "solution": [
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        1,
        3
      ],
      [
        0,
        3
      ],
      [
        0,
        2
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        1,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        2,
        3
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        3,
        3
      ],
      [
        3,
        2
      ],
      [
        3,
        1
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ]
    ],
    "difficulty": 5,
    "difficultyRaw": 55.8
  },
  {
    "id": 15,
    "size": 5,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 4
      },
      {
        "number": 2,
        "row": 0,
        "col": 0
      },
      {
        "number": 3,
        "row": 4,
        "col": 4
      },
      {
        "number": 4,
        "row": 2,
        "col": 1
      },
      {
        "number": 5,
        "row": 3,
        "col": 2
      },
      {
        "number": 6,
        "row": 4,
        "col": 0
      }
    ],
    "walls": [],
    "solution": [
      [
        0,
        4
      ],
      [
        0,
        3
      ],
      [
        0,
        2
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        1,
        1
      ],
      [
        1,
        2
      ],
      [
        1,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        4,
        3
      ],
      [
        3,
        3
      ],
      [
        2,
        3
      ],
      [
        2,
        2
      ],
      [
        2,
        1
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        4,
        1
      ],
      [
        4,
        0
      ]
    ],
    "difficulty": 4,
    "difficultyRaw": 51
  },
  {
    "id": 16,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 5
      },
      {
        "number": 2,
        "row": 3,
        "col": 3
      },
      {
        "number": 3,
        "row": 1,
        "col": 0
      },
      {
        "number": 4,
        "row": 5,
        "col": 0
      },
      {
        "number": 5,
        "row": 5,
        "col": 5
      }
    ],
    "walls": [
      {
        "row": 1,
        "col": 1,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 3,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 3,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 5,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 4,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 1,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 4,
        "direction": "right"
      }
    ],
    "solution": [
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        4,
        4
      ],
      [
        4,
        3
      ],
      [
        4,
        2
      ],
      [
        4,
        1
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        2,
        4
      ],
      [
        1,
        4
      ],
      [
        0,
        4
      ],
      [
        0,
        3
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        2,
        2
      ],
      [
        2,
        1
      ],
      [
        1,
        1
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        5,
        2
      ],
      [
        5,
        3
      ],
      [
        5,
        4
      ],
      [
        5,
        5
      ]
    ],
    "difficulty": 7,
    "difficultyRaw": 78.3
  },
  {
    "id": 17,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 4,
        "col": 0
      },
      {
        "number": 2,
        "row": 4,
        "col": 3
      },
      {
        "number": 3,
        "row": 5,
        "col": 5
      },
      {
        "number": 4,
        "row": 1,
        "col": 2
      },
      {
        "number": 5,
        "row": 0,
        "col": 5
      }
    ],
    "walls": [
      {
        "row": 1,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 3,
        "direction": "down"
      },
      {
        "row": 5,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 5,
        "direction": "down"
      },
      {
        "row": 4,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 1,
        "col": 1,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 4,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 3,
        "direction": "right"
      }
    ],
    "solution": [
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        5,
        2
      ],
      [
        4,
        2
      ],
      [
        4,
        1
      ],
      [
        3,
        1
      ],
      [
        3,
        0
      ],
      [
        2,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        5,
        4
      ],
      [
        5,
        5
      ],
      [
        4,
        5
      ],
      [
        3,
        5
      ],
      [
        2,
        5
      ],
      [
        1,
        5
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        2,
        3
      ],
      [
        1,
        3
      ],
      [
        1,
        2
      ],
      [
        0,
        2
      ],
      [
        0,
        3
      ],
      [
        0,
        4
      ],
      [
        0,
        5
      ]
    ],
    "difficulty": 6,
    "difficultyRaw": 74.7
  },
  {
    "id": 18,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "row": 5,
        "col": 0
      },
      {
        "number": 3,
        "row": 1,
        "col": 4
      },
      {
        "number": 4,
        "row": 5,
        "col": 5
      },
      {
        "number": 5,
        "row": 3,
        "col": 2
      }
    ],
    "walls": [
      {
        "row": 4,
        "col": 3,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 0,
        "direction": "down"
      },
      {
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "row": 4,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 3,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 0,
        "col": 1,
        "direction": "right"
      }
    ],
    "solution": [
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        5,
        3
      ],
      [
        4,
        3
      ],
      [
        3,
        3
      ],
      [
        2,
        3
      ],
      [
        1,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        5,
        5
      ],
      [
        4,
        5
      ],
      [
        3,
        5
      ],
      [
        2,
        5
      ],
      [
        1,
        5
      ],
      [
        0,
        5
      ],
      [
        0,
        4
      ],
      [
        0,
        3
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ]
    ],
    "difficulty": 6,
    "difficultyRaw": 74.7
  },
  {
    "id": 19,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "row": 0,
        "col": 5
      },
      {
        "number": 3,
        "row": 2,
        "col": 2
      },
      {
        "number": 4,
        "row": 5,
        "col": 0
      },
      {
        "number": 5,
        "row": 5,
        "col": 5
      },
      {
        "number": 6,
        "row": 3,
        "col": 4
      }
    ],
    "walls": [
      {
        "row": 3,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 5,
        "col": 1,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 3,
        "direction": "down"
      },
      {
        "row": 0,
        "col": 4,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 4,
        "direction": "down"
      },
      {
        "row": 4,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 1,
        "direction": "down"
      }
    ],
    "solution": [
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        0,
        3
      ],
      [
        0,
        4
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        1,
        4
      ],
      [
        1,
        3
      ],
      [
        1,
        2
      ],
      [
        1,
        1
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        3,
        1
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        5,
        3
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        5,
        5
      ],
      [
        4,
        5
      ],
      [
        3,
        5
      ],
      [
        2,
        5
      ],
      [
        2,
        4
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ]
    ],
    "difficulty": 6,
    "difficultyRaw": 69.8
  },
  {
    "id": 20,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "row": 0,
        "col": 5
      },
      {
        "number": 3,
        "row": 5,
        "col": 5
      },
      {
        "number": 4,
        "row": 3,
        "col": 3
      },
      {
        "number": 5,
        "row": 2,
        "col": 1
      },
      {
        "number": 6,
        "row": 5,
        "col": 0
      }
    ],
    "walls": [
      {
        "row": 3,
        "col": 3,
        "direction": "right"
      },
      {
        "row": 2,
        "col": 4,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 4,
        "direction": "down"
      },
      {
        "row": 4,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 5,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 2,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 1,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 0,
        "direction": "down"
      }
    ],
    "solution": [
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        0,
        3
      ],
      [
        0,
        4
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        5,
        5
      ],
      [
        5,
        4
      ],
      [
        5,
        3
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        3,
        4
      ],
      [
        2,
        4
      ],
      [
        1,
        4
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        3,
        2
      ],
      [
        3,
        1
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        1
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        5,
        1
      ],
      [
        5,
        0
      ]
    ],
    "difficulty": 6,
    "difficultyRaw": 73
  },
  {
    "id": 21,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 5,
        "col": 5
      },
      {
        "number": 2,
        "row": 0,
        "col": 5
      },
      {
        "number": 3,
        "row": 1,
        "col": 3
      },
      {
        "number": 4,
        "row": 3,
        "col": 3
      },
      {
        "number": 5,
        "row": 1,
        "col": 1
      },
      {
        "number": 6,
        "row": 5,
        "col": 0
      }
    ],
    "walls": [
      {
        "row": 4,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 4,
        "direction": "down"
      },
      {
        "row": 0,
        "col": 4,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 4,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 4,
        "col": 5,
        "direction": "down"
      },
      {
        "row": 1,
        "col": 3,
        "direction": "down"
      },
      {
        "row": 4,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 1,
        "col": 2,
        "direction": "right"
      }
    ],
    "solution": [
      [
        5,
        5
      ],
      [
        5,
        4
      ],
      [
        5,
        3
      ],
      [
        5,
        2
      ],
      [
        5,
        1
      ],
      [
        4,
        1
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        4,
        5
      ],
      [
        3,
        5
      ],
      [
        2,
        5
      ],
      [
        1,
        5
      ],
      [
        0,
        5
      ],
      [
        0,
        4
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        3,
        3
      ],
      [
        2,
        3
      ],
      [
        2,
        2
      ],
      [
        2,
        1
      ],
      [
        1,
        1
      ],
      [
        1,
        2
      ],
      [
        0,
        2
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ]
    ],
    "difficulty": 6,
    "difficultyRaw": 74.6
  },
  {
    "id": 22,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 4
      },
      {
        "number": 2,
        "row": 2,
        "col": 5
      },
      {
        "number": 3,
        "row": 3,
        "col": 3
      },
      {
        "number": 4,
        "row": 5,
        "col": 5
      },
      {
        "number": 5,
        "row": 5,
        "col": 1
      },
      {
        "number": 6,
        "row": 1,
        "col": 0
      }
    ],
    "walls": [
      {
        "row": 3,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 5,
        "direction": "down"
      },
      {
        "row": 1,
        "col": 3,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 1,
        "direction": "right"
      }
    ],
    "solution": [
      [
        0,
        4
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        3,
        4
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        4,
        5
      ],
      [
        5,
        5
      ],
      [
        5,
        4
      ],
      [
        5,
        3
      ],
      [
        5,
        2
      ],
      [
        5,
        1
      ],
      [
        5,
        0
      ],
      [
        4,
        0
      ],
      [
        3,
        0
      ],
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        3,
        2
      ],
      [
        2,
        2
      ],
      [
        2,
        3
      ],
      [
        1,
        3
      ],
      [
        0,
        3
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        1
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ]
    ],
    "difficulty": 6,
    "difficultyRaw": 66.6
  },
  {
    "id": 23,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 5,
        "col": 0
      },
      {
        "number": 2,
        "row": 4,
        "col": 2
      },
      {
        "number": 3,
        "row": 0,
        "col": 0
      },
      {
        "number": 4,
        "row": 2,
        "col": 3
      },
      {
        "number": 5,
        "row": 0,
        "col": 5
      },
      {
        "number": 6,
        "row": 4,
        "col": 4
      },
      {
        "number": 7,
        "row": 5,
        "col": 5
      }
    ],
    "walls": [
      {
        "row": 1,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 0,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 4,
        "direction": "right"
      },
      {
        "row": 2,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 1,
        "col": 4,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 2,
        "direction": "down"
      }
    ],
    "solution": [
      [
        5,
        0
      ],
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        5,
        1
      ],
      [
        5,
        2
      ],
      [
        5,
        3
      ],
      [
        4,
        3
      ],
      [
        4,
        2
      ],
      [
        3,
        2
      ],
      [
        3,
        1
      ],
      [
        3,
        0
      ],
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        1
      ],
      [
        1,
        0
      ],
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        2,
        4
      ],
      [
        1,
        4
      ],
      [
        0,
        4
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        5,
        5
      ]
    ],
    "difficulty": 6,
    "difficultyRaw": 66.6
  },
  {
    "id": 24,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 2,
        "col": 3
      },
      {
        "number": 2,
        "row": 5,
        "col": 5
      },
      {
        "number": 3,
        "row": 4,
        "col": 2
      },
      {
        "number": 4,
        "row": 0,
        "col": 5
      },
      {
        "number": 5,
        "row": 0,
        "col": 0
      },
      {
        "number": 6,
        "row": 5,
        "col": 0
      },
      {
        "number": 7,
        "row": 1,
        "col": 1
      }
    ],
    "walls": [
      {
        "row": 3,
        "col": 3,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 5,
        "direction": "down"
      }
    ],
    "solution": [
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        5,
        5
      ],
      [
        5,
        4
      ],
      [
        4,
        4
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        5,
        2
      ],
      [
        4,
        2
      ],
      [
        3,
        2
      ],
      [
        2,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        2,
        5
      ],
      [
        1,
        5
      ],
      [
        0,
        5
      ],
      [
        0,
        4
      ],
      [
        0,
        3
      ],
      [
        0,
        2
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        4,
        1
      ],
      [
        3,
        1
      ],
      [
        2,
        1
      ],
      [
        1,
        1
      ]
    ],
    "difficulty": 5,
    "difficultyRaw": 60.2
  },
  {
    "id": 25,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 2
      },
      {
        "number": 2,
        "row": 1,
        "col": 0
      },
      {
        "number": 3,
        "row": 5,
        "col": 0
      },
      {
        "number": 4,
        "row": 5,
        "col": 5
      },
      {
        "number": 5,
        "row": 4,
        "col": 2
      },
      {
        "number": 6,
        "row": 0,
        "col": 5
      },
      {
        "number": 7,
        "row": 2,
        "col": 3
      }
    ],
    "walls": [
      {
        "row": 4,
        "col": 1,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 1,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 2,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 1,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 4,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 3,
        "direction": "down"
      },
      {
        "row": 4,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 0,
        "col": 1,
        "direction": "right"
      },
      {
        "row": 2,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 3,
        "col": 4,
        "direction": "down"
      },
      {
        "row": 2,
        "col": 3,
        "direction": "right"
      }
    ],
    "solution": [
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        2,
        1
      ],
      [
        1,
        1
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        5,
        2
      ],
      [
        5,
        3
      ],
      [
        5,
        4
      ],
      [
        5,
        5
      ],
      [
        4,
        5
      ],
      [
        4,
        4
      ],
      [
        4,
        3
      ],
      [
        4,
        2
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        3,
        5
      ],
      [
        2,
        5
      ],
      [
        2,
        4
      ],
      [
        1,
        4
      ],
      [
        1,
        5
      ],
      [
        0,
        5
      ],
      [
        0,
        4
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ]
    ],
    "difficulty": 6,
    "difficultyRaw": 70
  },
  {
    "id": 26,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 5
      },
      {
        "number": 2,
        "row": 0,
        "col": 0
      },
      {
        "number": 3,
        "row": 1,
        "col": 3
      },
      {
        "number": 4,
        "row": 2,
        "col": 2
      },
      {
        "number": 5,
        "row": 5,
        "col": 0
      },
      {
        "number": 6,
        "row": 4,
        "col": 4
      },
      {
        "number": 7,
        "row": 3,
        "col": 1
      }
    ],
    "walls": [
      {
        "row": 0,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 5,
        "col": 3,
        "direction": "right"
      },
      {
        "row": 3,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "row": 1,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 1,
        "col": 5,
        "direction": "down"
      }
    ],
    "solution": [
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        1,
        4
      ],
      [
        0,
        4
      ],
      [
        0,
        3
      ],
      [
        0,
        2
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        1,
        1
      ],
      [
        1,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        2,
        2
      ],
      [
        2,
        1
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        5,
        3
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        5,
        5
      ],
      [
        4,
        5
      ],
      [
        3,
        5
      ],
      [
        2,
        5
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        3,
        3
      ],
      [
        3,
        2
      ],
      [
        3,
        1
      ]
    ],
    "difficulty": 6,
    "difficultyRaw": 66.6
  },
  {
    "id": 27,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "row": 3,
        "col": 1
      },
      {
        "number": 3,
        "row": 1,
        "col": 2
      },
      {
        "number": 4,
        "row": 2,
        "col": 4
      },
      {
        "number": 5,
        "row": 0,
        "col": 5
      },
      {
        "number": 6,
        "row": 5,
        "col": 4
      },
      {
        "number": 7,
        "row": 5,
        "col": 0
      }
    ],
    "walls": [
      {
        "row": 4,
        "col": 2,
        "direction": "down"
      },
      {
        "row": 4,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 1,
        "col": 1,
        "direction": "down"
      },
      {
        "row": 0,
        "col": 1,
        "direction": "down"
      }
    ],
    "solution": [
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        3,
        2
      ],
      [
        3,
        1
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        1
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        3,
        4
      ],
      [
        2,
        4
      ],
      [
        1,
        4
      ],
      [
        0,
        4
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        5,
        5
      ],
      [
        5,
        4
      ],
      [
        5,
        3
      ],
      [
        5,
        2
      ],
      [
        5,
        1
      ],
      [
        5,
        0
      ]
    ],
    "difficulty": 6,
    "difficultyRaw": 63.4
  },
  {
    "id": 28,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 5,
        "col": 5
      },
      {
        "number": 2,
        "row": 2,
        "col": 5
      },
      {
        "number": 3,
        "row": 4,
        "col": 4
      },
      {
        "number": 4,
        "row": 3,
        "col": 3
      },
      {
        "number": 5,
        "row": 0,
        "col": 4
      },
      {
        "number": 6,
        "row": 5,
        "col": 1
      },
      {
        "number": 7,
        "row": 1,
        "col": 0
      },
      {
        "number": 8,
        "row": 3,
        "col": 0
      }
    ],
    "walls": [],
    "solution": [
      [
        5,
        5
      ],
      [
        4,
        5
      ],
      [
        3,
        5
      ],
      [
        2,
        5
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        5,
        3
      ],
      [
        4,
        3
      ],
      [
        3,
        3
      ],
      [
        2,
        3
      ],
      [
        1,
        3
      ],
      [
        1,
        4
      ],
      [
        1,
        5
      ],
      [
        0,
        5
      ],
      [
        0,
        4
      ],
      [
        0,
        3
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        5,
        1
      ],
      [
        5,
        0
      ],
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        3,
        1
      ],
      [
        2,
        1
      ],
      [
        1,
        1
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ]
    ],
    "difficulty": 5,
    "difficultyRaw": 57
  },
  {
    "id": 29,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 2,
        "col": 5
      },
      {
        "number": 2,
        "row": 5,
        "col": 5
      },
      {
        "number": 3,
        "row": 5,
        "col": 0
      },
      {
        "number": 4,
        "row": 3,
        "col": 0
      },
      {
        "number": 5,
        "row": 1,
        "col": 4
      },
      {
        "number": 6,
        "row": 0,
        "col": 2
      },
      {
        "number": 7,
        "row": 3,
        "col": 2
      },
      {
        "number": 8,
        "row": 0,
        "col": 0
      }
    ],
    "walls": [
      {
        "row": 1,
        "col": 3,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 1,
        "direction": "right"
      }
    ],
    "solution": [
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        5,
        5
      ],
      [
        5,
        4
      ],
      [
        5,
        3
      ],
      [
        5,
        2
      ],
      [
        5,
        1
      ],
      [
        5,
        0
      ],
      [
        4,
        0
      ],
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        3,
        4
      ],
      [
        2,
        4
      ],
      [
        1,
        4
      ],
      [
        1,
        5
      ],
      [
        0,
        5
      ],
      [
        0,
        4
      ],
      [
        0,
        3
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        3,
        2
      ],
      [
        2,
        2
      ],
      [
        2,
        1
      ],
      [
        2,
        0
      ],
      [
        1,
        0
      ],
      [
        1,
        1
      ],
      [
        0,
        1
      ],
      [
        0,
        0
      ]
    ],
    "difficulty": 5,
    "difficultyRaw": 60.2
  },
  {
    "id": 30,
    "size": 6,
    "checkpoints": [
      {
        "number": 1,
        "row": 1,
        "col": 0
      },
      {
        "number": 2,
        "row": 5,
        "col": 0
      },
      {
        "number": 3,
        "row": 4,
        "col": 2
      },
      {
        "number": 4,
        "row": 0,
        "col": 2
      },
      {
        "number": 5,
        "row": 5,
        "col": 3
      },
      {
        "number": 6,
        "row": 5,
        "col": 5
      },
      {
        "number": 7,
        "row": 0,
        "col": 5
      },
      {
        "number": 8,
        "row": 2,
        "col": 4
      }
    ],
    "walls": [
      {
        "row": 3,
        "col": 4,
        "direction": "right"
      },
      {
        "row": 0,
        "col": 1,
        "direction": "right"
      },
      {
        "row": 1,
        "col": 0,
        "direction": "right"
      },
      {
        "row": 4,
        "col": 1,
        "direction": "right"
      }
    ],
    "solution": [
      [
        1,
        0
      ],
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        5,
        2
      ],
      [
        4,
        2
      ],
      [
        3,
        2
      ],
      [
        2,
        2
      ],
      [
        1,
        2
      ],
      [
        0,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        5,
        4
      ],
      [
        5,
        5
      ],
      [
        4,
        5
      ],
      [
        3,
        5
      ],
      [
        2,
        5
      ],
      [
        1,
        5
      ],
      [
        0,
        5
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ]
    ],
    "difficulty": 6,
    "difficultyRaw": 63.4
  }
];
