import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { generateLevel } from "../src/game/generator.js";
import { solvePuzzle } from "../src/game/solver.js";
import { validateLevelData } from "../src/game/validator.js";
import { buildLevelConfigs } from "../src/levels/levelConfigs.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const configs = buildLevelConfigs();
const levels = [];
const failures = [];

console.log(`Generating ${configs.length} levels...`);

// Placement + wall-carving is randomized, so a single seed can occasionally
// be unlucky for a harder config (e.g. many checkpoints on a large board),
// especially now that the final-checkpoint-must-be-last rule (see
// solver.js) makes uniqueness harder to reach for some placements. Retry a
// handful of alternate seeds with a larger budget before giving up on a
// config entirely, rather than dropping a level the first time it's hard.
const RETRY_SEED_OFFSETS = [0, 104729, 209463, 314197, 418927, 523603];

for (const config of configs) {
  const startedAt = Date.now();
  process.stdout.write(
    `  level ${config.id} (${config.size}x${config.size}, checkpoints=${config.checkpointCount})... `
  );

  const baseSeed = config.seed ?? config.id * 7919 + 13;
  let level = null;
  for (const offset of RETRY_SEED_OFFSETS) {
    level = generateLevel({
      ...config,
      seed: baseSeed + offset,
      maxPlacementAttempts: config.maxPlacementAttempts ?? 80,
      maxCarveAttempts: config.maxCarveAttempts ?? 800,
      solverNodeLimit: config.solverNodeLimit ?? 6_000_000,
    });
    if (level) break;
  }
  const ms = Date.now() - startedAt;

  if (!level) {
    console.log(`FAILED (${ms}ms, exhausted ${RETRY_SEED_OFFSETS.length} seeds)`);
    failures.push(config.id);
    continue;
  }

  // Independently re-verify with the exact solver + data validator before accepting.
  const dataCheck = validateLevelData(level);
  if (!dataCheck.valid) {
    console.log(`REJECTED (data invalid: ${dataCheck.errors.join("; ")})`);
    failures.push(config.id);
    continue;
  }

  const verify = solvePuzzle(level, { maxSolutions: 2, nodeLimit: 8_000_000 });
  if (!verify.solvable || verify.aborted || verify.solutionCount !== 1) {
    console.log(
      `REJECTED (solver found solutionCount=${verify.solutionCount}, aborted=${verify.aborted})`
    );
    failures.push(config.id);
    continue;
  }

  console.log(
    `OK  unique solution  walls=${level.walls.length}  difficulty=${level.difficulty}/10  (${ms}ms)`
  );
  levels.push(level);
}

if (failures.length) {
  console.warn(`\n${failures.length} level(s) failed to generate: ${failures.join(", ")}`);
}

if (levels.length < 30) {
  console.warn(
    `\nWARNING: only ${levels.length} verified levels produced (need >= 30). Consider raising attempt budgets or relaxing configs.`
  );
}

// Re-number ids sequentially in case some configs failed and were skipped.
levels.forEach((lvl, i) => {
  lvl.id = i + 1;
});

const fileContents = `// AUTO-GENERATED by scripts/generateLevels.js — do not edit by hand.
// Every level below has been proven to have EXACTLY ONE solution by the
// exact solver in src/game/solver.js before being written to this file.
// The "solution" field exists for development/testing/verification only
// and must never be shown to the player.

export const LEVELS = ${JSON.stringify(levels, null, 2)};
`;

const outPath = path.join(__dirname, "..", "src", "levels", "levels.js");
writeFileSync(outPath, fileContents);
console.log(`\nWrote ${levels.length} verified levels to ${path.relative(process.cwd(), outPath)}`);
